### ISSUE TITLE
Requesting NYT dataset and features

### ISSUE THREAD

**Issue by ajaynagesh** [diegma/relation-autoencoder#2]
Hi, 

Thanks for sharing this cool work. I was wondering if it would be possible to share the dataset associated with this work (the NYT linked/matched with Freebase) along with the features used in the paper. 

Thanks much,
Ajay

**Comment by ajaynagesh** [comment]
Dataset is available to those who have LDC licence. Thanks @diegma!

**Comment by vhientran** [comment]
Hi @ajaynagesh , Could you please give me the link of the dataset on LDC ? I cannot find out it. Thanks!

**Comment by ajaynagesh** [comment]
@angelotran05  I think it is this corpus https://catalog.ldc.upenn.edu/LDC2008T19 
But I am not very sure as it was a while back I looked at this and I am not the author of the present work. Hope that helps.

**Comment by vhientran** [comment]
Hi @ajaynagesh , Thank you for your help.
